name: "Release docker image on github"

on:
  push:
    branches: [master, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hjpotter92
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to github docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: hjpotter92
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            docker.pkg.github.com/hjpotter92/gktoday.in-scraper/latest:latest
            ghcr.io/hjpotter92/gktoday.in-scraper/latest:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
